name: Setup SukiSU-Ultra builtin

on:
  push:
  workflow_dispatch:

permissions: write-all

jobs:
  Setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - run: |
        curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s builtin
        git clone --depth 1 -b kernel-4.19 https://gitlab.com/simonpunk/susfs4ksu.git

    - name: Apply SUSFS pathes
      run: |
        cp susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch KernelSU/
        cp susfs4ksu/kernel_patches/50_add_susfs_in_kernel-4.19.patch .
        cp susfs4ksu/kernel_patches/fs/* fs/
        cp susfs4ksu/kernel_patches/include/linux/* include/linux/
        cd KernelSU
        patch -p1 < 10_enable_susfs_for_ksu.patch
        cd ..
        patch -p1 < 50_add_susfs_in_kernel.patch
